import { Reel, Story, LiveRoom, Conversation, NotificationItem, LiveGift, User } from './types';

export const CURRENT_USER: User = {
  id: 'usr_current',
  name: 'Alex Rivera',
  username: 'alexrivera',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
  verified: true,
  bio: 'Visual artist & electronic music producer 🎧 | Tokyo & LA 📍 | Creating interactive audio-visual reels',
  followersCount: 142800,
  followingCount: 486,
  likesCount: 2900000,
  isFollowing: false,
};

export const MOCK_USERS: User[] = [
  CURRENT_USER,
  {
    id: 'usr_1',
    name: 'Elena Vance',
    username: 'elenavance',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    verified: true,
    bio: 'Cyberpunk fashion designer & digital nomad ✨',
    followersCount: 382000,
    followingCount: 310,
    likesCount: 5200000,
    isFollowing: true,
  },
  {
    id: 'usr_2',
    name: 'Marcus Chen',
    username: 'marcusbeats',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    verified: true,
    bio: 'Synthesizers, modular rigs, and bass loops 🎹',
    followersCount: 91400,
    followingCount: 220,
    likesCount: 1100000,
    isFollowing: true,
  },
  {
    id: 'usr_3',
    name: 'Sophia Laurent',
    username: 'sophialux',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    verified: false,
    bio: 'Film photography & retro aesthetics 🎞️ Private gallery',
    followersCount: 45000,
    followingCount: 180,
    likesCount: 420000,
    isFollowing: false,
    isPrivate: true,
    connectionStatus: 'none',
  },
  {
    id: 'usr_4',
    name: 'Kai Takahashi',
    username: 'kaicodes',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    verified: true,
    bio: 'WebGL & Generative shaders ⚡ Building Pulse apps',
    followersCount: 63000,
    followingCount: 410,
    likesCount: 890000,
    isFollowing: true,
    isPrivate: false,
    connectionStatus: 'accepted',
  },
  {
    id: 'usr_5',
    name: 'Maya Lin',
    username: 'mayarhythm',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&auto=format&fit=crop&q=80',
    verified: false,
    bio: 'Street dance choreographer & fitness addict 💃 Private workspace',
    followersCount: 210000,
    followingCount: 520,
    likesCount: 3400000,
    isFollowing: false,
    isPrivate: true,
    connectionStatus: 'pending',
    isIncomingRequest: true,
  },
];

export const MOCK_STORIES: Story[] = [
  {
    id: 'story_me',
    user: CURRENT_USER,
    hasUnread: false,
    items: [
      {
        id: 'st_item_me_1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
        duration: 5,
        caption: 'Sound check before the midnight livestream 🎛️',
        timestamp: '1h ago',
      },
    ],
  },
  {
    id: 'story_1',
    user: MOCK_USERS[1], // Elena
    hasUnread: true,
    isLiveNow: false,
    items: [
      {
        id: 'st_item_1_1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80',
        duration: 5,
        caption: 'Tokyo runway backstage fittings 🪡✨',
        timestamp: '2h ago',
      },
      {
        id: 'st_item_1_2',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80',
        duration: 5,
        caption: 'Neon palette moodboard for Spring 2026',
        timestamp: '45m ago',
      },
    ],
  },
  {
    id: 'story_2',
    user: MOCK_USERS[2], // Marcus
    hasUnread: true,
    isLiveNow: true,
    items: [
      {
        id: 'st_item_2_1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&auto=format&fit=crop&q=80',
        duration: 5,
        caption: 'LIVE NOW on Pulse! Jamming on the analog synths 🎚️',
        timestamp: '10m ago',
      },
    ],
  },
  {
    id: 'story_3',
    user: MOCK_USERS[3], // Sophia
    hasUnread: true,
    isLiveNow: false,
    items: [
      {
        id: 'st_item_3_1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&auto=format&fit=crop&q=80',
        duration: 5,
        caption: 'Golden hour in Kyoto captured on 35mm 🎞️',
        timestamp: '4h ago',
      },
    ],
  },
  {
    id: 'story_4',
    user: MOCK_USERS[4], // Kai
    hasUnread: false,
    isLiveNow: false,
    items: [
      {
        id: 'st_item_4_1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
        duration: 5,
        caption: 'Interactive particle physics running in WebGPU 🚀',
        timestamp: '6h ago',
      },
    ],
  },
  {
    id: 'story_5',
    user: MOCK_USERS[5], // Maya
    hasUnread: true,
    isLiveNow: false,
    items: [
      {
        id: 'st_item_5_1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&auto=format&fit=crop&q=80',
        duration: 5,
        caption: 'New choreography dropping at 8 PM! 🔥',
        timestamp: '3h ago',
      },
    ],
  },
];

export const MOCK_REELS: Reel[] = [
  {
    id: 'reel_1',
    user: MOCK_USERS[1],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-dancing-in-a-party-with-neon-lights-42533-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    caption: 'Neon party nights in Shibuya 🌌 Dropped this custom LED jacket today! What do you guys think of the light sync?',
    tags: ['#CyberpunkFashion', '#TokyoVibes', '#PulseCreatives', '#Nightlife'],
    audioTrack: {
      title: 'Midnight Echoes (Pulse Remix)',
      artist: 'Marcus Chen ft. Elena Vance',
      albumCover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=100&auto=format&fit=crop&q=80',
    },
    likesCount: 48200,
    commentsCount: 1340,
    sharesCount: 5620,
    bookmarksCount: 3200,
    isLiked: false,
    isBookmarked: false,
    viewsCount: 320000,
    comments: [
      {
        id: 'c_1',
        user: MOCK_USERS[2],
        text: 'That bassdrop sync on the sleeves is insane! 🔥',
        likes: 245,
        isLiked: true,
        timestamp: '2h ago',
      },
      {
        id: 'c_2',
        user: MOCK_USERS[4],
        text: 'Did you code the addressable LEDs with Arduino or Raspberry Pi Pico?',
        likes: 89,
        timestamp: '1h ago',
      },
      {
        id: 'c_3',
        user: MOCK_USERS[5],
        text: 'I need this jacket for our upcoming dance performance!! 😍',
        likes: 64,
        timestamp: '30m ago',
      },
    ],
  },
  {
    id: 'reel_2',
    user: MOCK_USERS[2],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-playing-a-synthesizer-in-a-dark-room-42861-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format&fit=crop&q=80',
    caption: 'Cooking a new analog synth patch on the Prophet-6 🎹 Real time cutoff & resonance tweaking.',
    tags: ['#ModularSynth', '#StudioSession', '#SoundDesign', '#PulseAudio'],
    audioTrack: {
      title: 'Analog Warmth (Original Audio)',
      artist: 'Marcus Chen',
      albumCover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    },
    likesCount: 31500,
    commentsCount: 890,
    sharesCount: 2400,
    bookmarksCount: 4100,
    isLiked: true,
    isBookmarked: true,
    viewsCount: 184000,
    comments: [
      {
        id: 'c_4',
        user: MOCK_USERS[0],
        text: 'Love that low-end warmth! Dropping this in my set tonight.',
        likes: 120,
        timestamp: '3h ago',
      },
      {
        id: 'c_5',
        user: MOCK_USERS[3],
        text: 'The visual aesthetic matches the sonic tone so well ✨',
        likes: 42,
        timestamp: '1h ago',
      },
    ],
  },
  {
    id: 'reel_3',
    user: MOCK_USERS[5],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-urban-dancer-performing-in-a-parking-lot-42475-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=600&auto=format&fit=crop&q=80',
    caption: 'Urban freestyle choreography in downtown underground tunnels ⚡ Feel the rhythm and let it move you.',
    tags: ['#FreestyleDance', '#HipHopChoreo', '#PulseStage', '#Movement'],
    audioTrack: {
      title: 'Kinetic Flow (Speed Up)',
      artist: 'Pulse Beats Lab',
      albumCover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=100&auto=format&fit=crop&q=80',
    },
    likesCount: 92400,
    commentsCount: 3120,
    sharesCount: 14300,
    bookmarksCount: 8900,
    isLiked: false,
    isBookmarked: false,
    viewsCount: 680000,
    comments: [
      {
        id: 'c_6',
        user: MOCK_USERS[1],
        text: 'Your footwork is on another dimension Maya!! 💥',
        likes: 318,
        timestamp: '5h ago',
      },
    ],
  },
  {
    id: 'reel_4',
    user: MOCK_USERS[3],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-photographer-taking-photos-on-a-rooftop-at-sunset-42686-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=600&auto=format&fit=crop&q=80',
    caption: 'Golden hour roof photography in Shinjuku with 35mm Kodak Portra 400 🌇 Watch the light transition.',
    tags: ['#35mmFilm', '#PhotographyTips', '#GoldenHour', '#VisualArt'],
    audioTrack: {
      title: 'Sunset in Shinjuku',
      artist: 'Sophia Laurent & Chillhop',
      albumCover: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    },
    likesCount: 54100,
    commentsCount: 1210,
    sharesCount: 6900,
    bookmarksCount: 5500,
    isLiked: false,
    isBookmarked: false,
    viewsCount: 410000,
    comments: [],
  },
];

export const MOCK_LIVE_ROOMS: LiveRoom[] = [
  {
    id: 'live_1',
    title: '🎧 Live Modular Jam & Q&A | Making Beats from Scratch',
    host: MOCK_USERS[2], // Marcus
    category: 'Music',
    viewerCount: 3420,
    previewUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&auto=format&fit=crop&q=80',
    streamUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-playing-a-synthesizer-in-a-dark-room-42861-large.mp4',
    startedAt: '42m ago',
    tags: ['#ElectronicMusic', '#BeatMaking', '#LiveStudio'],
  },
  {
    id: 'live_2',
    title: '✨ Cyberpunk Runway Preview & Studio Behind The Scenes',
    host: MOCK_USERS[1], // Elena
    category: 'Creative',
    viewerCount: 5890,
    previewUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80',
    streamUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-dancing-in-a-party-with-neon-lights-42533-large.mp4',
    startedAt: '18m ago',
    tags: ['#FashionDesign', '#TokyoStyle', '#BTS'],
  },
  {
    id: 'live_3',
    title: '⚡ WebGL 3D Interactive Shaders Live Coding',
    host: MOCK_USERS[4], // Kai
    category: 'Trending',
    viewerCount: 1240,
    previewUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    streamUrl: '',
    startedAt: '1h ago',
    tags: ['#CreativeCoding', '#WebGL', '#TechLive'],
  },
  {
    id: 'live_4',
    title: '💃 Dance Studio Session: Learning the Viral Pulse Hook',
    host: MOCK_USERS[5], // Maya
    category: 'Music',
    viewerCount: 4610,
    previewUrl: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&auto=format&fit=crop&q=80',
    streamUrl: '',
    startedAt: '25m ago',
    tags: ['#DanceWorkshop', '#Cardio', '#LiveWorkout'],
  },
];

export const LIVE_GIFTS: LiveGift[] = [
  { id: 'g_heart', name: 'Pulse Spark', icon: '⚡', cost: 10, animationColor: '#f43f5e' },
  { id: 'g_fire', name: 'Neon Flame', icon: '🔥', cost: 50, animationColor: '#f97316' },
  { id: 'g_crown', name: 'Cyber Crown', icon: '👑', cost: 150, animationColor: '#eab308' },
  { id: 'g_diamond', name: 'Pulse Diamond', icon: '💎', cost: 300, animationColor: '#06b6d4' },
  { id: 'g_rocket', name: 'Supernova', icon: '🚀', cost: 500, animationColor: '#8b5cf6' },
  { id: 'g_planet', name: 'Cosmic Pulse', icon: '🪐', cost: 1000, animationColor: '#ec4899' },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    participant: MOCK_USERS[1], // Elena Vance
    lastMessage: 'Let me send you the jacket specs for the stage design!',
    lastMessageTime: '12:45 PM',
    unreadCount: 2,
    isOnline: true,
    messages: [
      {
        id: 'm_1_1',
        senderId: 'usr_1',
        text: 'Hey Alex! Loved your latest reel audio track 🙌',
        timestamp: '12:30 PM',
        isRead: true,
      },
      {
        id: 'm_1_2',
        senderId: 'usr_current',
        text: 'Thanks Elena! That neon sync you built was unreal.',
        timestamp: '12:35 PM',
        isRead: true,
      },
      {
        id: 'm_1_3',
        senderId: 'usr_1',
        text: 'Are you going to be at the Tokyo Pulse Creator summit next Friday?',
        timestamp: '12:40 PM',
        isRead: true,
      },
      {
        id: 'm_1_4',
        senderId: 'usr_1',
        text: 'Let me send you the jacket specs for the stage design!',
        timestamp: '12:45 PM',
        isRead: false,
      },
    ],
  },
  {
    id: 'conv_2',
    participant: MOCK_USERS[2], // Marcus Chen
    lastMessage: 'Sent an audio sample 🎵',
    lastMessageTime: '10:15 AM',
    unreadCount: 0,
    isOnline: true,
    messages: [
      {
        id: 'm_2_1',
        senderId: 'usr_2',
        text: 'Check out this 808 bass loop I rendered for our collaboration',
        timestamp: '10:12 AM',
        isRead: true,
      },
      {
        id: 'm_2_2',
        senderId: 'usr_2',
        mediaType: 'audio',
        text: 'Analog_Sub_140BPM_Drop.wav (0:15)',
        timestamp: '10:15 AM',
        isRead: true,
      },
    ],
  },
  {
    id: 'conv_3',
    participant: MOCK_USERS[3], // Sophia Laurent
    lastMessage: 'The film scan prints are ready!',
    lastMessageTime: 'Yesterday',
    unreadCount: 0,
    isOnline: false,
    messages: [
      {
        id: 'm_3_1',
        senderId: 'usr_3',
        text: 'The film scan prints are ready! Uploading previews now.',
        timestamp: 'Yesterday',
        isRead: true,
      },
    ],
  },
  {
    id: 'conv_4',
    participant: MOCK_USERS[4], // Kai Takahashi
    lastMessage: 'Awesome shader! Shared the repo link.',
    lastMessageTime: '2d ago',
    unreadCount: 0,
    isOnline: true,
    messages: [
      {
        id: 'm_4_1',
        senderId: 'usr_4',
        text: 'Awesome shader! Shared the repo link.',
        timestamp: '2d ago',
        isRead: true,
      },
    ],
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_conn_req_1',
    type: 'connection_request',
    actor: MOCK_USERS[5], // Maya Lin
    text: 'sent you a friend connection request',
    timestamp: '5m ago',
    isRead: false,
    connectionId: 'conn_maya_alex',
    connectionStatus: 'pending',
  },
  {
    id: 'notif_1',
    type: 'live',
    actor: MOCK_USERS[2],
    text: 'started a live broadcast: "🎧 Live Modular Jam & Q&A"',
    targetLiveId: 'live_1',
    timestamp: '10m ago',
    isRead: false,
  },
  {
    id: 'notif_2',
    type: 'gift',
    actor: MOCK_USERS[1],
    text: 'sent you a Supernova 🚀 gift in your live room!',
    timestamp: '35m ago',
    isRead: false,
  },
  {
    id: 'notif_3',
    type: 'like',
    actor: MOCK_USERS[3],
    text: 'liked your reel "Midnight Audio Visualizer in WebGPU"',
    targetReelThumbnail: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=200&auto=format&fit=crop&q=80',
    timestamp: '1h ago',
    isRead: false,
  },
  {
    id: 'notif_4',
    type: 'comment',
    actor: MOCK_USERS[5],
    text: 'commented: "That drop is so clean! 🔥 Choreographing to this today"',
    targetReelThumbnail: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=200&auto=format&fit=crop&q=80',
    timestamp: '2h ago',
    isRead: true,
  },
  {
    id: 'notif_5',
    type: 'mention',
    actor: MOCK_USERS[1],
    text: 'tagged you in a story: "Backstage sound check with @alexrivera"',
    timestamp: '4h ago',
    isRead: true,
  },
  {
    id: 'notif_6',
    type: 'follow',
    actor: MOCK_USERS[4],
    text: 'started following you on Pulse',
    timestamp: '1d ago',
    isRead: true,
    connectionStatus: 'accepted',
  },
];
